version: '3'

volumes:

  nextcloud-data:
  nextcloud-db:

networks:

  nextcloud-back:

  prodnetwork:
    external: true

services:

  nextcloud:
    image: nextcloud:13.0.0
    restart: always
    container_name: nextcloud
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    environment:
      - VIRTUAL_HOST=nextcloud.example.com
      - VIRUTAL_PORT=80
    networks:
      - nextcloud-back
      - prodnetwork
    volumes:
      - nextcloud-data:/var/www/html
      - /docker-volumes/nextcloud/nextcloud-data:/var/www/html
    ports:
      - "80" 

  nextcloud_db:
    image: mariadb
    restart: always
    container_name: nextcloud_db
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /docker-volumes/nextcloud/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
    - nextcloud-back

  nextcloud_cron:
    image: nextcloud:13.0.0
    restart: always
    container_name: nextcloud_cron
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    networks:
    - nextcloud-back
    links:
      - nextcloud_db
    volumes:
      - nextcloud-data:/var/www/html
      - /docker-volumes/nextcloud/nextcloud-data:/var/www/html
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        /usr/local/bin/php /var/www/html/cron.php
        sleep 900
      done
      EOF'


